### ISSUE TITLE
Package.json

### ISSUE THREAD

**Issue by shinyangdevelop** [StAiDev/BOJ-App#12]
일단 안에 got 라이브러리는 뭐 하는 라이브러리임? 그리고 윈도우에서는 build:all 쓰면 맥 빼고 빌드 되나? 그리고 마지막으로 build와 build:all의 차이가 뭐임?
@smartwe

**Comment by smartwe** [comment]
build는 현재 OS에 맞게 하는거고
build:all은 맥만가능

**Comment by shinyangdevelop** [comment]
Ok thx
